bulid(Chakra-UI)
Iraq-RBC-Capstones-2021/capstone-react-lets-work pull request #12
Opened 2021-10-07 11:31 UTC by NooraYaqub44

Chakra-UI installed and costume theme created for colors and fonts

2021-10-07 13:28 UTC, HaiderAltufaily approved these changes, later dismissed
Great work Noora!

Nit: It would be awesome if you could add custom styles for the Button component as well.

2021-10-07 14:25 UTC, MuhannedNoman requested changes
Hey @NooraYaqub44, nice work here. 
Left you some comments to make things better, let me know what you think!

2021-10-07 14:25 UTC, MuhannedNoman commented on pages/index.js
> +import { Text } from "@chakra-ui/react";
Why is this imported but not used?

2021-10-07 14:25 UTC, MuhannedNoman commented on src/theme/index.js
> +    60: "#EBEDFF",
Can we have a more clearer name for those fonts?

2021-10-07 14:25 UTC, MuhannedNoman commented on src/theme/index.js
> +import { extendTheme, theme as base } from "@chakra-ui/react";
Let's remove this theme file to `styles` folder.

2021-10-07 14:25 UTC, MuhannedNoman commented on pages/_app.js
> +import "../src/theme/styles.css";
Let's order those correctly. Start by stuff that is imported from the node_modules like 
```
import { ChakraProvider } from "@chakra-ui/provider";

import { wrapper } from "../store";
import "../styles/globals.css";
import theme from "../src/theme/index";
import "../src/theme/styles.css";
```

2021-10-07 14:25 UTC, MuhannedNoman commented on src/theme/styles.css
> +@import url("https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&family=Montserrat:wght@700&display=swap");
Let's make this a Font.js file and import the fonts correctly as shown [here](https://chakra-ui-git-fix-typescript-autocomplete.chakra-ui.vercel.app/guides/custom-fonts). 

PS: There is a Sandbox at the end of the page for a working demo.

2021-10-07 15:02 UTC, NooraYaqub44 commented on pages/index.js
> +import { Text } from "@chakra-ui/react";
Well it was for testing something but I forgot to remove it

2021-10-07 15:04 UTC, NooraYaqub44 commented on src/theme/styles.css
> +@import url("https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&family=Montserrat:wght@700&display=swap");
ok

2021-10-07 15:04 UTC, NooraYaqub44 commented on pages/_app.js
> +import "../src/theme/styles.css";
ok

2021-10-07 15:09 UTC, NooraYaqub44 commented on src/theme/index.js
> +import { extendTheme, theme as base } from "@chakra-ui/react";
ok

2021-10-07 15:10 UTC, NooraYaqub44 commented on src/theme/index.js
> +    60: "#EBEDFF",
These are colors that we are using but I didn't know how to name them but I do something with it

2021-10-07 16:08 UTC, aryankarim commented on pages/_app.js
> +import theme from "../src/theme/index";
You have deleted the `src` folder. This line is causing a Vercel build error.

2021-10-07 19:16 UTC, HaiderAltufaily commented on styles/theme/index.js
> +};
I think we should have at least 3 of our main colors that we are going to use here, you can keep the old colors object you created but only change the names something like :
```
const colors = {
  primary: {
    lighter: "#7884ff",
    main: "#5E6DFF",
    darker: "#4556ff",
  },

  secondary: {
    lighter: "#edeffd",
    main: "#EBEDFF",
    darker: "#d2d6ff",
  },
  tertiary: {
    lighter: "#244153",
    main: "#1C3341",
    darker: "#14252f",
  },};
```
You can change the names to whatever you like

2021-10-07 19:33 UTC, HaiderAltufaily commented on styles/theme/Fonts.js
> +        font-style: normal;
Since we have used Roboto font family in our design I think u should change the Open Sans and Raleway fonts to Roboto.
Note: I actually recommend using fontsource to install the fonts instead of using a separate fonts file with a lot of code we can simply install roboto with `npm install @fontsource/roboto`  then we `import "@fontsource/roboto"`in our _app file and finally adding it to our `theme.js` file:
`const fonts = {
  heading: "",
  body: "Roboto",
};`
for details check the first option in: https://chakra-ui.com/guides/using-fonts

2021-10-08 10:40 UTC, MuhannedNoman approved these changes
Nice work @NooraYaqub44 LGTM, feel free to merge.

2021-10-08 11:00 UTC, HaiderAltufaily approved these changes

2021-10-08 11:03 UTC, merged