create the top section of the home page
Iraq-RBC-Capstones-2021/capstone-react-lets-work pull request #15
Opened 2021-10-08 14:34 UTC by EsraaY21

Fixes #8

2021-10-08 16:48 UTC, HaiderAltufaily requested changes
Great work Esraa, the design is perfect but there are few things that should be changed I think
I'll mention them in the comments

2021-10-08 16:52 UTC, HaiderAltufaily commented on pages/index.js
> +            Let's Work
First of all let's fix the deploy error, it is caused by eslint: we shouldn't use this character (') inside our text so you can do one of these solutions:
1- `//eslint-disable-next-line ` before the line 29
2- instead of writing Let's Work, write it like this `Let&apos;s Work;` as mentioned here https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-unescaped-entities.md

2021-10-08 16:56 UTC, HaiderAltufaily commented on pages/index.js
> +      </Container>
For the images try to use next/image as it is a feature of nextjs and also don't forget to use the `alt` attribute 
details: https://nextjs.org/docs/api-reference/next/image

2021-10-08 17:05 UTC, IsraaY21 commented on pages/index.js
> +            Let's Work
Thank you so much! I will do that.

2021-10-08 17:07 UTC, HaiderAltufaily reviewed
And do you think it is better to use the pages folder as a container and transfer this code to the components folder something like `/components/Home/TopSection.js` and then import it to `/pages/index.js`

2021-10-08 19:15 UTC, EsraaY21 commented
@HaiderAltufaily  now the code works on vercel. Can you check it please when you have time

2021-10-08 20:19 UTC, HaiderAltufaily approved these changes
LGTM, Awesome work

2021-10-09 14:35 UTC, MuhannedNoman approved these changes
LGTM nice work here @EsraaY21 Feel free to merge.

2021-10-09 14:39 UTC, merged