style(SignIn&SignUp): add styles for sign in and signup pages
Iraq-RBC-Capstones-2021/capstone-react-lets-work pull request #26
Opened 2021-10-09 12:42 UTC by HaiderAltufaily

## What?
Created Sign In and Sign Up pages along with their components

## Note:
In order to view the changes go to `/signin` or `/signup` in the preview page

2021-10-09 13:31 UTC, EsraaY21 commented
Looks amazing! Great work =)

2021-10-09 13:35 UTC, EsraaY21 approved these changes

2021-10-09 14:50 UTC, MuhannedNoman approved these changes
Hey @HaiderAltufaily nice work here, but why is eslint disabled in a few components?

2021-10-09 14:50 UTC, MuhannedNoman commented on components/SignIn/ForgotPass.js
> +/* eslint-disable react/no-children-prop */
Why are we disabling eslint here?

2021-10-09 15:00 UTC, HaiderAltufaily commented on components/SignIn/ForgotPass.js
> +/* eslint-disable react/no-children-prop */
In chakra ui you need to use children as a prop and eslint considers this as an error so I had to disable it 
ex:
`  <InputLeftElement
                    pointerEvents="none"
                    fontSize="lg"
                    h="46px"
                    children={<BiEnvelope size="20" />}
                  />`
This gave me an error because I used children as a prop here....

2021-10-09 16:28 UTC, HaiderAltufaily commented on components/SignIn/ForgotPass.js
> +/* eslint-disable react/no-children-prop */
@MuhannedNoman Should I look for another solution to this problem?

2021-10-09 18:11 UTC, MuhannedNoman commented on components/SignIn/ForgotPass.js
> +/* eslint-disable react/no-children-prop */
Can you disable it for next line only.

2021-10-09 18:12 UTC, MuhannedNoman commented
Also, @HaiderAltufaily what are you using for validating the data like password!?

2021-10-09 18:35 UTC, HaiderAltufaily commented on components/SignIn/ForgotPass.js
> +/* eslint-disable react/no-children-prop */
Okay I will do that

2021-10-09 18:50 UTC, HaiderAltufaily commented
Umm, I thought I should only make the design and I didn't do anything for the validation yet... I was planning to do them when I start working on the firebase authentication as firebase has its own email&pass validation and error messages...
So should I work on validation now? @MuhannedNoman

2021-10-09 22:16 UTC, HaiderAltufaily commented
I have created a custom input hook and validated each data with error messages... and also I have made custom Input styling (both primary and error variants). More error messages will be added once we work on the firebase authentication...
With these changes, can I have a new review..?

2021-10-10 09:02 UTC, EsraaY21 requested changes
Great work! The sing up page works perfectly but here is a small problem with the password validation. It doesn't show me an error when I type a password smaller than 6.

2021-10-10 09:21 UTC, EsraaY21 approved these changes
Nice! LGTM =)

2021-10-10 20:27 UTC, MuhannedNoman commented
> 
> 
> I have created a custom input hook and validated each data with error messages... and also I have made custom Input styling (both primary and error variants). More error messages will be added once we work on the firebase authentication... With these changes, can I have a new review..?

This is only a simple validation, using a library you can do a more complicated validation for symbol, number of letters, ...etc. 
Also, using a library here is considered front end validation so it has nothing to do with firebase or any other service used for the back-end

2021-10-11 16:11 UTC, HaiderAltufaily commented
Hey @MuhannedNoman I have refactored the code and these are the main changes:
## Changes:
- Deleted the custom hook and instead used formik and yup for validation
- created a shared folder inside the components, inside this folder I have created a `ChakraInput` and `ChakraCheckbox` in these components I have utilized chakra ui `Input` with the `Field` component of formik.
- Used ChakraInput inside sign in and sign up pages which reduced the code a lot
- Recreated `forgotPass.js` but it's much simpler now.
- added arabic language for both of the pages (Didn't add it for the error messages yet) to check go to: 
https://capstone-react-lets-work-git-haideraltufaily-issue7-lets-work.vercel.app/ar/signin

2021-10-12 15:09 UTC, MuhannedNoman approved these changes
LGTM nice work here @HaiderAltufaily

2021-10-12 18:24 UTC, EsraaY21 approved these changes
Great Work!

2021-10-12 18:38 UTC, merged