style:Create the idea Card in profile
Iraq-RBC-Capstones-2021/capstone-react-lets-work pull request #31
Opened 2021-10-11 12:08 UTC by EsraaY21

issue #16

2021-10-11 12:11 UTC, EsraaY21 commented
Note: To see the changes go to `/account`

2021-10-11 12:20 UTC, aryankarim submitted a review, later dismissed
Good work! let us know if you have any problems resolving those conflicts!

2021-10-11 12:59 UTC, EsraaY21 commented
@aryanmajeed Thank you so much! I will =D

2021-10-12 15:06 UTC, MuhannedNoman requested changes
Nice work here @EsraaY21 Can you take a look at the comments I left here and le me know what you think!

2021-10-12 15:06 UTC, MuhannedNoman commented on public/images/pexels-photo-355948 2.png:Zone.Identifier
> +[ZoneTransfer]
Didn't those .Identifier files cause issues as @HaiderAltufaily noted in #33 ?

2021-10-12 15:06 UTC, MuhannedNoman commented on components/Account/IdeaCard.js
> +const IdeaCard = ({ ideaImage, title, userImage, username, date }) => {
Can we also add the href of the project so that when we click on the card we go there?

2021-10-12 15:24 UTC, IsraaY21 commented on public/images/pexels-photo-355948 2.png:Zone.Identifier
> +[ZoneTransfer]
Yes, I will remove them.

2021-10-12 15:27 UTC, IsraaY21 commented on components/Account/IdeaCard.js
> +const IdeaCard = ({ ideaImage, title, userImage, username, date }) => {
Ok, I will do that.

2021-10-14 07:50 UTC, MuhannedNoman submitted a review, later dismissed
LGTM, but is the about page and card supposed to be in this PR?

2021-10-14 10:37 UTC, EsraaY21 commented
I already did the about page and merged it but then I wanted to do very small changes so I thought I could do that here. I forgot that I needed to create an issue for that.

2021-10-14 11:56 UTC, aryanmajeed approved these changes

2021-10-14 12:17 UTC, merged