Noora yaqub44/issue22
Iraq-RBC-Capstones-2021/capstone-react-lets-work pull request #34
Opened 2021-10-12 14:50 UTC by NooraYaqub44

This is the Comment component but for now, I put the file inside pages so it would be easy to see and also used another background color so it could be easy to see and I will fix these two things after I get approvment.

2021-10-12 14:58 UTC, MuhannedNoman requested changes
Hey, @NooraYaqub44 looks good, added a few comments to make things better. Let me know what you think.

2021-10-12 14:58 UTC, MuhannedNoman commented on pages/Comment.js
> +    likes: "56",
Let's have those passed to the component so we can use it, later on, like so. Also, let's add the logic to handle replay to comment functionality. The structure can be something like this [post ](https://stackoverflow.com/a/65010510)or [video ](https://www.youtube.com/watch?v=Hxgbiunp2DA)are doing

2021-10-14 13:06 UTC, aryankarim approved these changes
Fix the conflicts, and implement Muhanned's note. Let me know if you need any help. Otherwise, this looks good.

2021-10-18 10:22 UTC, MuhannedNoman approved these changes
LGTM, feel free to merge.

2021-10-18 10:43 UTC, merged