Noora yaqub44/issue18
Iraq-RBC-Capstones-2021/capstone-react-lets-work pull request #37
Opened 2021-10-14 18:06 UTC by NooraYaqub44

This is the top section for the profile page, you can find it in "/account"

2021-10-14 19:57 UTC, HaiderAltufaily requested changes
Great work Noora, there are only few things mainly about the colors ill mention them in the comments

2021-10-14 20:00 UTC, HaiderAltufaily commented on components/Profile/TopSection.js
> +              Segun Adebayo
First of all I think it is better if we make an object representing the user and then rendering his info, something like:
```
const user = {
  username: "Segun Adebayo",
  bio: "Web Developer",
  about: "I love Web development and I have been coding for last ten years",
  interests: ["Web", "Design", "HTML & Javascript"],
  skills_hobbies: ["Web Development", "Hiking"],
  social:{ instagram:"", facebook:"", email:"", linkedIn:""
  }
};
```

2021-10-14 20:01 UTC, HaiderAltufaily commented on components/Profile/TopSection.js
> +      <Box bg="gray.200" px="150px" py="68px">
I think the background color must be` "secondary.main`" as it is in the figma design 

and for the Button we have a custom style you can easily use for it `<Button variant="primary">` because the default one disappears on hover

2021-10-14 20:09 UTC, HaiderAltufaily commented on components/Profile/TopSection.js
> +            </HStack>
For these social images it would be great if you can make them something like: `<IconButton as={Link} href={user.social.instagram} children={ < SiInstagram/> } />`

2021-10-14 20:13 UTC, HaiderAltufaily commented
Also, check the responsiveness for mobile screens

2021-10-14 22:05 UTC, aryankarim approved these changes
Great work! Also, Haider wrote some great notes. If you could do those that would be excellent. And, let me know if you need any help.

2021-10-14 22:14 UTC, aryankarim commented on components/Profile/TopSection.js
> +              I love Web development and I have been coding for last ten years
Also `gray.400` is a little too bright, making it a little darker will give it more visibility and contrast.

2021-10-16 11:32 UTC, MuhannedNoman commented
The mobile view is off here.

2021-10-16 18:45 UTC, NooraYaqub44 commented
I have fixed the mobile and tablet mode just have some problem with image aligment

2021-10-16 20:08 UTC, NooraYaqub44 commented
all the problems fixed @MuhannedNoman @aryanmajeed

2021-10-17 16:37 UTC, HaiderAltufaily approved these changes
LGTM, nice work

2021-10-17 17:21 UTC, NooraYaqub44 commented
@MuhannedNoman

2021-10-17 17:22 UTC, NooraYaqub44 commented
@aryanmajeed

2021-10-18 10:32 UTC, MuhannedNoman approved these changes
After implementing the changes and the weird space above (if applicable here). Feel free to merge!

2021-10-18 10:32 UTC, MuhannedNoman commented on components/Profile/TopSection.js
> +    social: { instagram: "", facebook: "", email: "", linkedIn: "" },
Let's get this info as props and display it here.

2021-10-18 10:32 UTC, MuhannedNoman commented on components/Profile/TopSection.js
> +            emerged into consciousness.
Prop as well.

2021-10-18 11:59 UTC, merged